import error

pub fn solutions() -> Result(#(Int, Int), error.AocError) {
    Ok(#(0, 0))
}
